### ISSUE TITLE
Factory default u-boot cannot access SD card

### ISSUE THREAD

**Issue by ghost** [MIPS/CI20_u-boot#2]
The factory default u-boot on NAND cannot load a kernel from SD Card.

The mmc commands just hang.

**Comment by ZubairLK** [comment]
looks similar to issue number 1 :)

https://github.com/MIPS/CI20_u-boot/issues/1

**Comment by ghost** [comment]
Ah yes, I hadn't twigged that one was from SD card, sorry!
